/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Time = IDL.Int;
export const CoinType = IDL.Variant({
  'icp' : IDL.Null,
  'ckBtc' : IDL.Null,
  'ckEth' : IDL.Null,
  'ckSol' : IDL.Null,
  'infinityCoin' : IDL.Null,
});
export const TransactionHistoryItem = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Text,
  'amountE8' : IDL.Nat,
  'sender' : IDL.Principal,
  'blockHeight' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'coinType' : CoinType,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'getBalances' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCurrentRates' : IDL.Func([], [IDL.Text], []),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionHistoryItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordBalance' : IDL.Func([CoinType, IDL.Nat], [], []),
  'recordTransaction' : IDL.Func(
      [IDL.Text, IDL.Nat, CoinType, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Time = IDL.Int;
  const CoinType = IDL.Variant({
    'icp' : IDL.Null,
    'ckBtc' : IDL.Null,
    'ckEth' : IDL.Null,
    'ckSol' : IDL.Null,
    'infinityCoin' : IDL.Null,
  });
  const TransactionHistoryItem = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Text,
    'amountE8' : IDL.Nat,
    'sender' : IDL.Principal,
    'blockHeight' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'coinType' : CoinType,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'getBalances' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCurrentRates' : IDL.Func([], [IDL.Text], []),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionHistoryItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordBalance' : IDL.Func([CoinType, IDL.Nat], [], []),
    'recordTransaction' : IDL.Func(
        [IDL.Text, IDL.Nat, CoinType, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };