/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CoinType = { 'icp' : null } |
  { 'ckBtc' : null } |
  { 'ckEth' : null } |
  { 'ckSol' : null } |
  { 'infinityCoin' : null };
export interface Contact {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'address' : string,
}
export type Time = bigint;
export interface TransactionHistoryItem {
  'id' : bigint,
  'recipient' : string,
  'amountE8' : bigint,
  'sender' : Principal,
  'blockHeight' : [] | [bigint],
  'timestamp' : Time,
  'coinType' : CoinType,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'getBalances' : ActorMethod<[], [bigint, bigint, bigint, bigint, bigint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getCurrentRates' : ActorMethod<[], string>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionHistoryItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordBalance' : ActorMethod<[CoinType, bigint], undefined>,
  'recordTransaction' : ActorMethod<
    [string, bigint, CoinType, [] | [bigint]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContact' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContact' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];